### ISSUE TITLE
你好，最近点击“开始直播”会有闪退的Bug

### ISSUE THREAD

**Issue by jjzjx118** [tiantianlan/miaoboDemo#1]
使用日期 12-19-2016 打开程序后点击底部按钮 然后点击开始直播 会闪退并且报LFLiveKite里的一个野指针Bug，请问要如何修复呢？
![snip20161219_8](https://cloud.githubusercontent.com/assets/19865763/21306179/ad062122-c60a-11e6-9643-951f29b344db.png)

**Comment by guoxiaopang** [comment]
![image](https://cloud.githubusercontent.com/assets/11028035/21307212/7e5736b8-c60f-11e6-8162-acb276b61dbc.png)
stream.url 需要修改为你的服务器地址。 比如像@"http://192.168.1.1"这样的。  否则他读取URL地址会错误。 服务器配置请参考文章。

**Comment by jjzjx118** [comment]
非常感谢 ，后来我自己看到了XD，感觉自己好蠢哈哈~

**Comment by jjzjx118** [comment]
您好，我想再问一下。如果自己写Demo测试，我在本地配置好了nginx服务器，然后在 stream.url写的rtmp://localhost:1234/liveTest/room 似乎推不上去，显示的是连接错误。在本地使用ffmpeg 推流，用VLC播放（地址就是rtmp://localhost:1234/liveTest/room）是可以的。但是写进项目就不行了。不知道是为何呢？手机和电脑（server）是在同一个wifi里的。但是不知道从手机是否可以直接用rtmp://localhost:1234/liveTest/room链接自己的nginx服务器。我猜测是server地址不能写localhost... 求指教了。

**Comment by guoxiaopang** [comment]
URL地址里写localhost后，在手机上解析的时候localhost就不是你电脑的地址了，而是指手机，此时你手机上并没有nginx服务器。

**Comment by jjzjx118** [comment]
噢，原来是这样。那请问我要如何往自己电脑上的nginx服务器推流呢？

**Comment by guoxiaopang** [comment]
直接写电脑的ip地址。

**Comment by jjzjx118** [comment]
你好，我在电脑的网络偏好设置里发现IPv4地址为：192.168.0.62 。然后我在前面加了http://192.168.0.62 。之后设置ATS 允许http访问。 然后推流 链接状态一直是“链接中”。
之后尝试在本地推流，然后手机拉流地址也是填写的 http://192.168.0.62 。观察到命令行有正常推流，但是手机端还是什么都没有拉到。不知道是什么情况呢？感觉还是IP地址没有填写对。。。

**Comment by guoxiaopang** [comment]
需要加上你在nginx配置的rtmp端口号（我的教程里面是1935），不加默认监听的80或者8080。 这是网站访问的端口。
如果你推流的地址还带路径的话，拉流的时候还需要做端口号后面加上路径。比如像：rtmp://localhost:1935/rtmplive/room这样的

**Comment by jjzjx118** [comment]
你好，我的nginx配置是这样的：
`rtmp {
    server {
        listen 1234;
        application liveTest {
            live on;
            record off;
        }
    }
}`

然后在本地nginx推流，观测到正常推流后，尝试了手机拉流：
`  _player = [[IJKFFMoviePlayerController alloc] initWithContentURLString:@"rtmp://192.168.0.62:1234/liveTest/room" withOptions:options];
  _player = [[IJKFFMoviePlayerController alloc] initWithContentURLString:@"http://192.168.0.62:1234/liveTest/room" withOptions:options];
`
这2种地址都尝试了，但是都没有成功。请问前缀是用rtmp还是http呢？谢谢了。

**Comment by guoxiaopang** [comment]
本地nginx推流正常后，先下载一个VLC(播放器)测试一下是否能够播放，能够播放再把VLC里面的地址填写在手机里测试。  前缀使用rtmp

**Comment by jjzjx118** [comment]
是的，我从手机推流地址是：http://192.168.0.62:1234/liveTest/room 然后VLC是可以拉到手机的流的。 VLC播放地址是：rtmp://localhost:1234/liveTest/room。但是手机端 拉流地址肯定不能写localhost。我写的是：@"rtmp://192.168.0.62:1234/liveTest/room"提示错误：`Cannot open connection tcp://192.168.0.62:1234
rtmp://192.168.0.62:1234/liveTest/room: Operation timed out`
尝试了@"http://192.168.0.62:1234/liveTest/room" 但是很久也拉不到流，提示：`http://192.168.0.62:1234/liveTest/room: Operation timed out
2016-12-22 11:53:56.334140 liveTest[1223:390861] FFP_MSG_ERROR: 0`
请问拉流和推流的地址是一模一样的吗？

**Comment by jjzjx118** [comment]
汇报一下，已经成功了。拉不到的原因是那个手机没跟电脑在同一个wifi。。。 谢谢你一直以来的帮助：）。 不过如果想从外网来访问本地nginx服务器就不行了，正在研究XD~

**Comment by guoxiaopang** [comment]
我不了解你那边的具体情况。 如果你想使用手机拉流，你得在服务端推流，或者用另外一台手机推流。
